### ISSUE TITLE
Same player can join the same game multiple times

### ISSUE THREAD

**Issue by RealmportalMC** [SugarCaney/CrystalQuest#5] opened 2019-07-03 14:51 UTC
When players join a game, they are able to keep right clicking the sign and joining the same game multiple times causing Crystalquest to think there are X more players in the game. I join the orange team, im still able to right click again and join green as well.

CQ 1.3.2 , Paper 1.12.2

**Comment by SugarCaney** [comment] 2019-07-03 17:34
Dont put your lobby signs in the arena lobbies? Or am I missing something?

**Comment by RealmportalMC** [comment] 2019-07-03 20:09
you shouldnt be able to do that to start with. Just block ppl from joining if your already in a game. 

Because you can do the same thing with /cq join

**Comment by SugarCaney** [comment] 2019-07-03 22:54
Odd, because there is a check for that in [/cq join](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/command/CommandJoin.java#L62). Same goes for the [join signs](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/listeners/SignListener.java#L258).

And the [ArenaManager](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/game/ArenaManager.java#L165) also [seems to be fine](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/game/Arena.java#L430).

Are you sure the setup is correct? Because this is either a setup issue, or an issue with players not joining correctly (which I doubt when [looking](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/listeners/InventoryListener.java#L141) at the [code](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/game/Arena.java#L1026)). But who knows.. Any remarkable exceptions in the console?

Edit: The code looks horrible in some places... So much for child labour..

**Comment by RealmportalMC** [comment] 2019-07-03 22:55
> 
> 
> Odd, because there is a check for that in [/cq join](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/command/CommandJoin.java#L62). Same goes for the [join signs](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/listeners/SignListener.java#L258).
> 
> And the [ArenaManager](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/game/ArenaManager.java#L165) also [seems to be fine](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/game/Arena.java#L430).
> 
> Are you sure the setup is correct? Because this is either a setup issue, or an issue with players not joining correctly (which I doubt when [looking](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/listeners/InventoryListener.java#L141) at the [code](https://github.com/SugarCaney/CrystalQuest/blob/7ff75c455aa78751c4a9400fc908874d90333f1d/src/nl/sugcube/crystalquest/game/Arena.java#L1026)). But who knows.. Any remarkable exceptions in the console?

Ill go check again

**Comment by RealmportalMC** [comment] 2019-07-03 22:58
I can join green, then join orage, then join green again, each time it registers as a new player joining the game.

![2019-07-03_17 56 12](https://user-images.githubusercontent.com/22693741/60629622-0e400580-9dbc-11e9-94a4-e2cd2171deb4.png)
I also get this error upon the game starting

java.lang.NullPointerException: null
[07/03/2019 05:56:43 pm]: at nl.sugcube.crystalquest.game.GameLoop.doGameLoop(GameLoop.java:105) ~[?:?]
[07/03/2019 05:56:43 pm]: at nl.sugcube.crystalquest.game.GameLoop.run(GameLoop.java:238) ~[?:?]
[07/03/2019 05:56:43 pm]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1596]
[07/03/2019 05:56:43 pm]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1596]
[07/03/2019 05:56:43 pm]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1596]
[07/03/2019 05:56:43 pm]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1596]
[07/03/2019 05:56:43 pm]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1596]
[07/03/2019 05:56:43 pm]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1596]
[07/03/2019 05:56:43 pm]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by HannahSchellekens** [comment] 2019-07-03 23:10
I'll take a look at it tomorrow as I'm heading to bed now. It's definitely an interesting issue. Would you mind sharing your data.yml?

Also, you're on 1.12 right? Because I'm already updating toward 1.14.x and it might already have been fixed there. I suppose you want a fix on 1.12?

**Comment by SugarCaney** [comment] 2019-07-03 23:11
I'll take a look at it tomorrow as I'm heading to bed now. It's definitely an interesting issue. Would you mind sharing your data.yml?

Also, you're on 1.12 right? Because I'm already updating toward 1.14.x and it might already have been fixed there. I suppose you want a fix on 1.12?

**Comment by RealmportalMC** [comment] 2019-07-03 23:48
yea, just important bug fixes, im not concerned about new features

**Comment by SugarCaney** [comment] 2019-07-04 08:57
I tested it on the 1.13/1.14 update, and it works fine there. I can reproduce it in 1.12, but I have no clue yet what causes it.

Temporary Workaround: Make sure that there are no join signs in the arena lobby to prevent joining through signs, and remove the `crystalquest.join` permission. Drawback is that `/cq join` no longer works, but it will prevent duplicate entries in arenas.

**Comment by SugarCaney** [comment] 2019-07-04 09:25
I just fixed it already, so the repo showed the correct version obviously. [Fixed on the 1.12 repository](https://github.com/SugarCaney/CrystalQuest-1.12.2/commit/32e9ac01ae076cc76709671f7ba4bb7f81cf0c03). Updated version v1.3.3 can be downloaded [there as well](https://github.com/SugarCaney/CrystalQuest-1.12.2/releases/tag/v1.3.3). Build on BukkitDev follows soon.

**Comment by RealmportalMC** [comment] 2019-07-08 03:11
its fixed in 1.3.3

**Closed as completed** 2020-05-24 23:40 UTC
Labels: bug
